server:
  port: 53030
app:
  id: account-service
apollo:
  meta: http://172.168.20.220:8080
  bootstrap:
    enabled: true
    namespaces: application,micro_service.spring-boot-druid,micro_service.spring-boot-http,micro_service.spring-eureka,micro_service.spring-hystrix,micro_service.spring-ribbon,micro_service.spring-boot-redis,micro_service.mybatis-plus,micro_service.spring-rocketmq,micro_service.spring-cloud-hmily
spring:
  application:
    name: account-service
# 日志配置-会代替springboot原生日志颜色
logging:
  config: classpath:log4j2-dev.xml





